/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clientetelespectador;

import java.util.ArrayList;

/**
 *
 * @author willi
 */
public class TelaInicial extends javax.swing.JFrame {

    ClienteTelespectador gerenciador = ClienteTelespectador.getInstance();
    
    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
        ClienteTelespectador.getInstance().conectar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Teste");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(321, 321, 321)
                .addComponent(jButton1)
                .addContainerGap(382, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(jButton1)
                .addContainerGap(192, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        gerenciador = ClienteTelespectador.getInstance();
        System.out.println("################    Teste   #######################");
        System.out.println("Etapa: " + gerenciador.getEtapa());
        System.out.println("Tempo do Quali: " + gerenciador.getTempoQuali());
        System.out.println("Num de Voltas: " + gerenciador.getNumVoltas());
        System.out.println("Pista: " + gerenciador.getNomePista());
        System.out.println("Autor do record: " + gerenciador.getRecordista());
        System.out.println("Record: " + gerenciador.getRecord());
        ArrayList<Piloto> pilotos = gerenciador.getPilotos();
        for(int i=0; i < pilotos.size(); i++){
            System.out.println("##################################");
            System.out.println("Piloto: " + Integer.toString(i));
            System.out.println("Nome: " +pilotos.get(i).getNome());
            System.out.println("Carro: " +pilotos.get(i).getCarro());
            System.out.println("Equipe: " +pilotos.get(i).getEquipe());
            System.out.println("Pos: " +pilotos.get(i).getPos());
            System.out.println("Voltas: " +pilotos.get(i).getVoltas());
            System.out.println("Tempo da volta: " +pilotos.get(i).getTempoVolta());
            System.out.println("Melhor volta: " +pilotos.get(i).getTempoMelhor());
            System.out.println("Tempo geral: " +pilotos.get(i).getTempoGeral());
            System.out.println("Tempo para o da frente: " +pilotos.get(i).getTempoCima());
            System.out.println("Tempo para o de trás: " +pilotos.get(i).getTempoBaixo());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
